/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Calend3 } from "./Calend3";
export * as factories from "./factories";
export { Calend3__factory } from "./factories/Calend3__factory";
